apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  Service__DeploymentType: {{ .Values.config.deploymentType | quote }}
  Service__DefaultWorkerName: {{ .Values.config.defaultWorkerName | quote }}
  Service__BatchLimit: {{ .Values.config.batchLimit | quote }}
  Service__WorkerIntervalSeconds: {{ .Values.config.workerIntervalSeconds | quote }}
  Service__SyncIntervalInSeconds: {{ .Values.config.syncIntervalInSeconds | quote }}
  Service__CriticalSyncIntervalInSeconds: {{ .Values.config.criticalSyncIntervalInSeconds | quote }}
  Service__BatchSaveSize: {{ .Values.config.batchSaveSize | quote }}
  Service__StartWeekend: {{ .Values.config.startWeekend | quote }}
  Service__SyncMode: {{ .Values.config.syncMode | quote }}
  Service__SyncType: {{ .Values.config.syncType | quote }}
  Service__ConcurrencyConfiguration__MaxParallelProcessingUsers: {{ .Values.config.maxParallelProcessingUsers | quote }}
  Service__ConcurrencyConfiguration__MaxUsersPerAdmin: {{ .Values.config.maxUsersPerAdmin | quote }}
  Service__FullSyncConfiguration__ProcessAttachments: {{ .Values.config.fullSyncProcessAttachments | quote }}
  Service__SensitiveSyncConfiguration__SensitiveTitle: {{ .Values.config.sensitiveTitle | quote }}
  Service__SensitiveSyncConfiguration__SensitiveCategory: {{ .Values.config.sensitiveCategory | quote }}
  Serilog__MinimumLevel__Default: {{ .Values.config.serilogMinLevel | quote }}
  Service__LoggingConfiguration__LogsOutput: {{ .Values.config.logsOutput | quote }}
  Service__LoggingConfiguration__LokiInternalUrl: {{ .Values.config.lokiInternalUrl | quote }}
  Service__LoggingConfiguration__LogFileSizeLimit: {{ .Values.config.logFileSizeLimit | quote }}
  Service__LoggingConfiguration__LogFileAmountLimit: {{ .Values.config.logFileAmountLimit | quote }}