apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-secondary
  labels:
    app: {{ .Release.Name }}
    component: secondary
spec:
  replicas: {{ .Values.secondary.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: secondary
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: secondary
    spec:
      containers:
        - name: sync-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: Service__IsPrimary
              value: "false"
          volumeMounts:
            - name: env-volume
              mountPath: /app/.env
              subPath: .env
            - name: settings-volume
              mountPath: /app/settings/admins.json
              subPath: admins.json
            - name: logs-volume
              mountPath: /app/logs
      volumes:
        - name: env-volume
          secret:
            secretName: {{ .Release.Name }}-env-file
        - name: settings-volume
          secret:
            secretName: {{ .Release.Name }}-exchange-admins
        - name: logs-volume
          emptyDir: {}